import { Material, Service } from './types';

export const INITIAL_MATERIALS: Material[] = [
  // ELECTRICAL
  { id: 'm1', order: 1, name: 'Fio Flexível 1,5mm² - Preto', category: 'eletrico', price: 2.5, unit: 'metro' },
  { id: 'm2', order: 2, name: 'Fio Flexível 2,5mm² - Azul', category: 'eletrico', price: 3.8, unit: 'metro' },
  { id: 'm3', order: 3, name: 'Fio Flexível 4,0mm² - Verde', category: 'eletrico', price: 5.9, unit: 'metro' },
  { id: 'm4', order: 4, name: 'Fio Flexível 6,0mm² - Vermelho', category: 'eletrico', price: 8.5, unit: 'metro' },
  { id: 'm5', order: 5, name: 'Disjuntor Monopolar 10A', category: 'eletrico', price: 12.0, unit: 'unidade' },
  { id: 'm6', order: 6, name: 'Disjuntor Monopolar 20A', category: 'eletrico', price: 12.0, unit: 'unidade' },
  { id: 'm7', order: 7, name: 'Disjuntor Bipolar 40A', category: 'eletrico', price: 45.0, unit: 'unidade' },
  { id: 'm8', order: 8, name: 'Tomada 10A Branca', category: 'eletrico', price: 15.0, unit: 'unidade' },
  { id: 'm9', order: 9, name: 'Interruptor Simples', category: 'eletrico', price: 12.0, unit: 'unidade' },
  { id: 'm10', order: 10, name: 'Caixa 4x2 PVC', category: 'eletrico', price: 1.5, unit: 'unidade' },
  { id: 'm11', order: 11, name: 'Eletroduto Flexível 3/4"', category: 'eletrico', price: 3.0, unit: 'metro' },
  { id: 'm12', order: 12, name: 'Lâmpada LED 9W', category: 'eletrico', price: 9.0, unit: 'unidade' },
  { id: 'm13', order: 13, name: 'Fita Isolante 20m', category: 'eletrico', price: 8.0, unit: 'unidade' },
  { id: 'm14', order: 14, name: 'Conector Wago 2 polos', category: 'eletrico', price: 3.5, unit: 'unidade' },
  
  // HYDRAULIC
  // PPR SECTION
  { id: 'm15', order: 15, name: 'PPR Tubo 20 mm x 3 m', category: 'hidraulico', price: 45.0, unit: 'unidade' },
  { id: 'm16', order: 16, name: 'PPR Cap 20 mm', category: 'hidraulico', price: 3.5, unit: 'unidade' },
  { id: 'm17', order: 17, name: 'PPR Curva 45° 20 mm', category: 'hidraulico', price: 8.0, unit: 'unidade' },
  { id: 'm18', order: 18, name: 'PPR Curva 90° curta 20 mm', category: 'hidraulico', price: 7.5, unit: 'unidade' },
  { id: 'm19', order: 19, name: 'PPR Luva 20 mm', category: 'hidraulico', price: 3.0, unit: 'unidade' },
  { id: 'm20', order: 20, name: 'PPR Tê 90° 20 mm', category: 'hidraulico', price: 9.0, unit: 'unidade' },
  { id: 'm21', order: 21, name: 'PPR União 20 mm', category: 'hidraulico', price: 11.0, unit: 'unidade' },
  { id: 'm22', order: 22, name: 'PPR Redução 20x25 mm', category: 'hidraulico', price: 5.0, unit: 'unidade' },
  { id: 'm23', order: 23, name: 'PPR Adaptador macho rosca 20x1/2"', category: 'hidraulico', price: 12.0, unit: 'unidade' },
  { id: 'm24', order: 24, name: 'PPR Adaptador fêmea rosca 20x1/2"', category: 'hidraulico', price: 12.0, unit: 'unidade' },
  { id: 'm25', order: 25, name: 'PPR Bucha de redução 20x25 mm', category: 'hidraulico', price: 6.0, unit: 'unidade' },
  { id: 'm26', order: 26, name: 'PPR Joelho 90° com rosca interna 20 mm', category: 'hidraulico', price: 13.0, unit: 'unidade' },
  { id: 'm27', order: 27, name: 'PPR Joelho 90° com rosca externa 20 mm', category: 'hidraulico', price: 13.0, unit: 'unidade' },
  { id: 'm28', order: 28, name: 'PPR Válvula esférica 20 mm', category: 'hidraulico', price: 35.0, unit: 'unidade' },
  { id: 'm29', order: 29, name: 'PPR Registro esfera 20 mm', category: 'hidraulico', price: 38.0, unit: 'unidade' },
  { id: 'm30', order: 30, name: 'PPR Tubo 25 mm x 3 m', category: 'hidraulico', price: 60.0, unit: 'unidade' },
  { id: 'm31', order: 31, name: 'PPR Cap 25 mm', category: 'hidraulico', price: 4.5, unit: 'unidade' },
  { id: 'm32', order: 32, name: 'PPR Curva 45° 25 mm', category: 'hidraulico', price: 10.0, unit: 'unidade' },
  { id: 'm33', order: 33, name: 'PPR Curva 90° curta 25 mm', category: 'hidraulico', price: 9.5, unit: 'unidade' },
  { id: 'm34', order: 34, name: 'PPR Luva 25 mm', category: 'hidraulico', price: 4.0, unit: 'unidade' },
  { id: 'm35', order: 35, name: 'PPR Tê 90° 25 mm', category: 'hidraulico', price: 11.0, unit: 'unidade' },
  { id: 'm36', order: 36, name: 'PPR União 25 mm', category: 'hidraulico', price: 14.0, unit: 'unidade' },
  { id: 'm37', order: 37, name: 'PPR Redução 25x32 mm', category: 'hidraulico', price: 6.5, unit: 'unidade' },
  { id: 'm38', order: 38, name: 'PPR Adaptador macho rosca 25x3/4"', category: 'hidraulico', price: 14.0, unit: 'unidade' },
  { id: 'm39', order: 39, name: 'PPR Adaptador fêmea rosca 25x3/4"', category: 'hidraulico', price: 14.0, unit: 'unidade' },
  { id: 'm40', order: 40, name: 'PPR Bucha de redução 25x32 mm', category: 'hidraulico', price: 7.0, unit: 'unidade' },
  { id: 'm41', order: 41, name: 'PPR Joelho 90° com rosca interna 25 mm', category: 'hidraulico', price: 15.0, unit: 'unidade' },
  { id: 'm42', order: 42, name: 'PPR Válvula esférica 25 mm', category: 'hidraulico', price: 42.0, unit: 'unidade' },
  { id: 'm43', order: 43, name: 'PPR Tubo 32 mm x 3 m', category: 'hidraulico', price: 80.0, unit: 'unidade' },
  { id: 'm44', order: 44, name: 'PPR Cap 32 mm', category: 'hidraulico', price: 6.0, unit: 'unidade' },
  { id: 'm45', order: 45, name: 'PPR Curva 45° 32 mm', category: 'hidraulico', price: 13.0, unit: 'unidade' },
  { id: 'm46', order: 46, name: 'PPR Curva 90° curta 32 mm', category: 'hidraulico', price: 12.5, unit: 'unidade' },
  { id: 'm47', order: 47, name: 'PPR Luva 32 mm', category: 'hidraulico', price: 5.5, unit: 'unidade' },
  { id: 'm48', order: 48, name: 'PPR Tê 90° 32 mm', category: 'hidraulico', price: 14.0, unit: 'unidade' },
  { id: 'm49', order: 49, name: 'PPR União 32 mm', category: 'hidraulico', price: 18.0, unit: 'unidade' },
  { id: 'm50', order: 50, name: 'PPR Redução 32x40 mm', category: 'hidraulico', price: 8.0, unit: 'unidade' },
  { id: 'm51', order: 51, name: 'PPR Adaptador macho rosca 32x1"', category: 'hidraulico', price: 16.0, unit: 'unidade' },
  { id: 'm52', order: 52, name: 'PPR Adaptador fêmea rosca 32x1"', category: 'hidraulico', price: 16.0, unit: 'unidade' },
  { id: 'm53', order: 53, name: 'PPR Joelho 90° com rosca interna 32 mm', category: 'hidraulico', price: 18.0, unit: 'unidade' },
  { id: 'm54', order: 54, name: 'PPR Válvula esférica 32 mm', category: 'hidraulico', price: 55.0, unit: 'unidade' },
  { id: 'm55', order: 55, name: 'PPR Tubo 40 mm x 3 m', category: 'hidraulico', price: 110.0, unit: 'unidade' },
  { id: 'm56', order: 56, name: 'PPR Cap 40 mm', category: 'hidraulico', price: 8.0, unit: 'unidade' },
  { id: 'm57', order: 57, name: 'PPR Curva 45° 40 mm', category: 'hidraulico', price: 17.0, unit: 'unidade' },
  { id: 'm58', order: 58, name: 'PPR Curva 90° curta 40 mm', category: 'hidraulico', price: 16.0, unit: 'unidade' },
  { id: 'm59', order: 59, name: 'PPR Luva 40 mm', category: 'hidraulico', price: 7.5, unit: 'unidade' },
  { id: 'm60', order: 60, name: 'PPR Tê 90° 40 mm', category: 'hidraulico', price: 18.0, unit: 'unidade' },
  { id: 'm61', order: 61, name: 'PPR União 40 mm', category: 'hidraulico', price: 24.0, unit: 'unidade' },
  { id: 'm62', order: 62, name: 'PPR Redução 40x50 mm', category: 'hidraulico', price: 10.0, unit: 'unidade' },
  { id: 'm63', order: 63, name: 'PPR Adaptador macho rosca 40x1.1/4"', category: 'hidraulico', price: 20.0, unit: 'unidade' },
  { id: 'm64', order: 64, name: 'PPR Válvula esférica 40 mm', category: 'hidraulico', price: 70.0, unit: 'unidade' },
  { id: 'm65', order: 65, name: 'PPR Tubo 50 mm x 3 m', category: 'hidraulico', price: 150.0, unit: 'unidade' },
  { id: 'm66', order: 66, name: 'PPR Cap 50 mm', category: 'hidraulico', price: 10.0, unit: 'unidade' },
  { id: 'm67', order: 67, name: 'PPR Curva 45° 50 mm', category: 'hidraulico', price: 22.0, unit: 'unidade' },
  { id: 'm68', order: 68, name: 'PPR Curva 90° curta 50 mm', category: 'hidraulico', price: 21.0, unit: 'unidade' },
  { id: 'm69', order: 69, name: 'PPR Luva 50 mm', category: 'hidraulico', price: 9.5, unit: 'unidade' },
  { id: 'm70', order: 70, name: 'PPR Tê 90° 50 mm', category: 'hidraulico', price: 23.0, unit: 'unidade' },
  { id: 'm71', order: 71, name: 'PPR União 50 mm', category: 'hidraulico', price: 30.0, unit: 'unidade' },
  { id: 'm72', order: 72, name: 'PPR Adaptador macho rosca 50x1.1/2"', category: 'hidraulico', price: 25.0, unit: 'unidade' },
  { id: 'm73', order: 73, name: 'PPR Válvula esférica 50 mm', category: 'hidraulico', price: 95.0, unit: 'unidade' },
  { id: 'm74', order: 74, name: 'PPR Tubo 63 mm x 3 m', category: 'hidraulico', price: 240.0, unit: 'unidade' },
  { id: 'm75', order: 75, name: 'PPR Cap 63 mm', category: 'hidraulico', price: 15.0, unit: 'unidade' },
  { id: 'm76', order: 76, name: 'PPR Curva 45° 63 mm', category: 'hidraulico', price: 32.0, unit: 'unidade' },
  { id: 'm77', order: 77, name: 'PPR Curva 90° curta 63 mm', category: 'hidraulico', price: 30.0, unit: 'unidade' },
  { id: 'm78', order: 78, name: 'PPR Luva 63 mm', category: 'hidraulico', price: 14.0, unit: 'unidade' },
  { id: 'm79', order: 79, name: 'PPR Tê 90° 63 mm', category: 'hidraulico', price: 35.0, unit: 'unidade' },
  { id: 'm80', order: 80, name: 'PPR União 63 mm', category: 'hidraulico', price: 45.0, unit: 'unidade' },
  { id: 'm81', order: 81, name: 'PPR Válvula esférica 63 mm', category: 'hidraulico', price: 130.0, unit: 'unidade' },

  // CPVC SECTION
  { id: 'm82', order: 82, name: 'CPVC Tubo 22 mm x 3 m', category: 'hidraulico', price: 60.0, unit: 'unidade' },
  { id: 'm83', order: 83, name: 'CPVC Cap 22 mm', category: 'hidraulico', price: 1.9, unit: 'unidade' },
  { id: 'm84', order: 84, name: 'CPVC Curva 45° 22 mm', category: 'hidraulico', price: 10.0, unit: 'unidade' },
  { id: 'm85', order: 85, name: 'CPVC Curva 90° 22 mm', category: 'hidraulico', price: 12.5, unit: 'unidade' },
  { id: 'm86', order: 86, name: 'CPVC Luva 22 mm', category: 'hidraulico', price: 3.0, unit: 'unidade' },
  { id: 'm87', order: 87, name: 'CPVC Tê 90° 22 mm', category: 'hidraulico', price: 4.9, unit: 'unidade' },
  { id: 'm88', order: 88, name: 'CPVC União 22 mm', category: 'hidraulico', price: 20.0, unit: 'unidade' },
  { id: 'm89', order: 89, name: 'CPVC Redução 22x28 mm', category: 'hidraulico', price: 9.9, unit: 'unidade' },
  { id: 'm90', order: 90, name: 'CPVC Adaptador macho rosca 22x3/4"', category: 'hidraulico', price: 19.9, unit: 'unidade' },
  { id: 'm91', order: 91, name: 'CPVC Adaptador fêmea rosca 22x3/4"', category: 'hidraulico', price: 19.9, unit: 'unidade' },
  { id: 'm92', order: 92, name: 'CPVC Joelho 90° com rosca interna 22 mm', category: 'hidraulico', price: 13.0, unit: 'unidade' },
  { id: 'm93', order: 93, name: 'CPVC Válvula esférica 22 mm', category: 'hidraulico', price: 40.0, unit: 'unidade' },
  { id: 'm94', order: 94, name: 'CPVC Tubo 28 mm x 3 m', category: 'hidraulico', price: 85.0, unit: 'unidade' },
  { id: 'm95', order: 95, name: 'CPVC Cap 28 mm', category: 'hidraulico', price: 5.2, unit: 'unidade' },
  { id: 'm96', order: 96, name: 'CPVC Curva 45° 28 mm', category: 'hidraulico', price: 15.0, unit: 'unidade' },
  { id: 'm97', order: 97, name: 'CPVC Curva 90° 28 mm', category: 'hidraulico', price: 22.0, unit: 'unidade' },
  { id: 'm98', order: 98, name: 'CPVC Luva 28 mm', category: 'hidraulico', price: 8.7, unit: 'unidade' },
  { id: 'm99', order: 99, name: 'CPVC Tê 90° 28 mm', category: 'hidraulico', price: 11.0, unit: 'unidade' },
  { id: 'm100', order: 100, name: 'CPVC União 28 mm', category: 'hidraulico', price: 26.0, unit: 'unidade' },
  { id: 'm101', order: 101, name: 'CPVC Redução 28x22 mm', category: 'hidraulico', price: 3.9, unit: 'unidade' },
  { id: 'm102', order: 102, name: 'CPVC Adaptador macho rosca 28x1"', category: 'hidraulico', price: 26.0, unit: 'unidade' },
  { id: 'm103', order: 103, name: 'CPVC Adaptador fêmea rosca 28x1"', category: 'hidraulico', price: 26.0, unit: 'unidade' },
  { id: 'm104', order: 104, name: 'CPVC Joelho 90° com rosca interna 28 mm', category: 'hidraulico', price: 20.0, unit: 'unidade' },
  { id: 'm105', order: 105, name: 'CPVC Válvula esférica 28 mm', category: 'hidraulico', price: 55.0, unit: 'unidade' },
  { id: 'm106', order: 106, name: 'CPVC Tubo 35 mm x 3 m', category: 'hidraulico', price: 110.0, unit: 'unidade' },
  { id: 'm107', order: 107, name: 'CPVC Cap 35 mm', category: 'hidraulico', price: 6.5, unit: 'unidade' },
  { id: 'm108', order: 108, name: 'CPVC Curva 45° 35 mm', category: 'hidraulico', price: 18.0, unit: 'unidade' },
  { id: 'm109', order: 109, name: 'CPVC Curva 90° 35 mm', category: 'hidraulico', price: 20.0, unit: 'unidade' },
  { id: 'm110', order: 110, name: 'CPVC Luva 35 mm', category: 'hidraulico', price: 10.0, unit: 'unidade' },
  { id: 'm111', order: 111, name: 'CPVC Tê 90° 35 mm', category: 'hidraulico', price: 15.0, unit: 'unidade' },
  { id: 'm112', order: 112, name: 'CPVC União 35 mm', category: 'hidraulico', price: 30.0, unit: 'unidade' },
  { id: 'm113', order: 113, name: 'CPVC Adaptador macho rosca 35 mm', category: 'hidraulico', price: 28.0, unit: 'unidade' },
  { id: 'm114', order: 114, name: 'CPVC Tubo 42 mm x 3 m', category: 'hidraulico', price: 140.0, unit: 'unidade' },
  { id: 'm115', order: 115, name: 'CPVC Cap 42 mm', category: 'hidraulico', price: 8.0, unit: 'unidade' },
  { id: 'm116', order: 116, name: 'CPVC Curva 45° 42 mm', category: 'hidraulico', price: 22.0, unit: 'unidade' },
  { id: 'm117', order: 117, name: 'CPVC Curva 90° 42 mm', category: 'hidraulico', price: 25.0, unit: 'unidade' },
  { id: 'm118', order: 118, name: 'CPVC Luva 42 mm', category: 'hidraulico', price: 12.0, unit: 'unidade' },
  { id: 'm119', order: 119, name: 'CPVC Tê 90° 42 mm', category: 'hidraulico', price: 20.0, unit: 'unidade' },
  { id: 'm120', order: 120, name: 'CPVC União 42 mm', category: 'hidraulico', price: 35.0, unit: 'unidade' },
  { id: 'm121', order: 121, name: 'CPVC Válvula esférica 42 mm', category: 'hidraulico', price: 80.0, unit: 'unidade' },
  { id: 'm122', order: 122, name: 'CPVC Tubo 50 mm x 3 m', category: 'hidraulico', price: 180.0, unit: 'unidade' },
  { id: 'm123', order: 123, name: 'CPVC Cap 50 mm', category: 'hidraulico', price: 10.0, unit: 'unidade' },
  { id: 'm124', order: 124, name: 'CPVC Curva 45° 50 mm', category: 'hidraulico', price: 28.0, unit: 'unidade' },
  { id: 'm125', order: 125, name: 'CPVC Curva 90° 50 mm', category: 'hidraulico', price: 30.0, unit: 'unidade' },
  { id: 'm126', order: 126, name: 'CPVC Luva 50 mm', category: 'hidraulico', price: 15.0, unit: 'unidade' },
  { id: 'm127', order: 127, name: 'CPVC Tê 90° 50 mm', category: 'hidraulico', price: 25.0, unit: 'unidade' },
  { id: 'm128', order: 128, name: 'CPVC União 50 mm', category: 'hidraulico', price: 40.0, unit: 'unidade' },
  { id: 'm129', order: 129, name: 'CPVC Tubo 54 mm x 3 m', category: 'hidraulico', price: 250.0, unit: 'unidade' },
  { id: 'm130', order: 130, name: 'CPVC Cap 54 mm', category: 'hidraulico', price: 18.0, unit: 'unidade' },
  { id: 'm131', order: 131, name: 'CPVC Curva 90° 54 mm', category: 'hidraulico', price: 50.0, unit: 'unidade' },
  { id: 'm132', order: 132, name: 'CPVC Tê 90° 54 mm', category: 'hidraulico', price: 60.0, unit: 'unidade' },

  // PVC SOLDÁVEL SECTION
  // PVC 20 mm
  { id: 'm133', order: 133, name: 'PVC Soldável Tubo 20 mm x 3 m', category: 'hidraulico', price: 12.9, unit: 'unidade' },
  { id: 'm134', order: 134, name: 'PVC Soldável Cap 20 mm', category: 'hidraulico', price: 1.8, unit: 'unidade' },
  { id: 'm135', order: 135, name: 'PVC Soldável Curva 45° 20 mm', category: 'hidraulico', price: 2.9, unit: 'unidade' },
  { id: 'm136', order: 136, name: 'PVC Soldável Curva 90° curta 20 mm', category: 'hidraulico', price: 3.0, unit: 'unidade' },
  { id: 'm137', order: 137, name: 'PVC Soldável Joelho 90° 20 mm', category: 'hidraulico', price: 3.2, unit: 'unidade' },
  { id: 'm138', order: 138, name: 'PVC Soldável Luva 20 mm', category: 'hidraulico', price: 1.5, unit: 'unidade' },
  { id: 'm139', order: 139, name: 'PVC Soldável Tê 90° 20 mm', category: 'hidraulico', price: 2.7, unit: 'unidade' },
  { id: 'm140', order: 140, name: 'PVC Soldável União 20 mm', category: 'hidraulico', price: 3.8, unit: 'unidade' },
  { id: 'm141', order: 141, name: 'PVC Soldável Redução 20x25 mm', category: 'hidraulico', price: 2.4, unit: 'unidade' },
  { id: 'm142', order: 142, name: 'PVC Soldável Adaptador macho rosca 20x1/2"', category: 'hidraulico', price: 4.5, unit: 'unidade' },
  { id: 'm143', order: 143, name: 'PVC Soldável Adaptador fêmea rosca 20x1/2"', category: 'hidraulico', price: 4.5, unit: 'unidade' },
  { id: 'm144', order: 144, name: 'PVC Soldável Joelho 90° com bucha latão 20x1/2"', category: 'hidraulico', price: 10.9, unit: 'unidade' },
  { id: 'm145', order: 145, name: 'PVC Soldável Luva com bucha latão 20x1/2"', category: 'hidraulico', price: 7.9, unit: 'unidade' },
  { id: 'm146', order: 146, name: 'PVC Soldável Tê com bucha latão 20x1/2"', category: 'hidraulico', price: 12.5, unit: 'unidade' },
  { id: 'm147', order: 147, name: 'PVC Soldável Registro esfera 20 mm', category: 'hidraulico', price: 18.0, unit: 'unidade' },

  // PVC 25 mm
  { id: 'm148', order: 148, name: 'PVC Soldável Tubo 25 mm x 3 m', category: 'hidraulico', price: 16.5, unit: 'unidade' },
  { id: 'm149', order: 149, name: 'PVC Soldável Cap 25 mm', category: 'hidraulico', price: 2.2, unit: 'unidade' },
  { id: 'm150', order: 150, name: 'PVC Soldável Curva 45° 25 mm', category: 'hidraulico', price: 3.4, unit: 'unidade' },
  { id: 'm151', order: 151, name: 'PVC Soldável Curva 90° curta 25 mm', category: 'hidraulico', price: 3.6, unit: 'unidade' },
  { id: 'm152', order: 152, name: 'PVC Soldável Joelho 90° 25 mm', category: 'hidraulico', price: 3.8, unit: 'unidade' },
  { id: 'm153', order: 153, name: 'PVC Soldável Luva 25 mm', category: 'hidraulico', price: 1.9, unit: 'unidade' },
  { id: 'm154', order: 154, name: 'PVC Soldável Tê 90° 25 mm', category: 'hidraulico', price: 3.2, unit: 'unidade' },
  { id: 'm155', order: 155, name: 'PVC Soldável União 25 mm', category: 'hidraulico', price: 4.5, unit: 'unidade' },
  { id: 'm156', order: 156, name: 'PVC Soldável Redução 25x32 mm', category: 'hidraulico', price: 2.8, unit: 'unidade' },
  { id: 'm157', order: 157, name: 'PVC Soldável Adaptador macho rosca 25x3/4"', category: 'hidraulico', price: 5.5, unit: 'unidade' },
  { id: 'm158', order: 158, name: 'PVC Soldável Adaptador fêmea rosca 25x3/4"', category: 'hidraulico', price: 5.5, unit: 'unidade' },
  { id: 'm159', order: 159, name: 'PVC Soldável Joelho 90° com bucha latão 25x3/4"', category: 'hidraulico', price: 12.5, unit: 'unidade' },
  { id: 'm160', order: 160, name: 'PVC Soldável Luva com bucha latão 25x3/4"', category: 'hidraulico', price: 9.5, unit: 'unidade' },
  { id: 'm161', order: 161, name: 'PVC Soldável Tê com bucha latão 25x3/4"', category: 'hidraulico', price: 15.0, unit: 'unidade' },
  { id: 'm162', order: 162, name: 'PVC Soldável Registro esfera 25 mm', category: 'hidraulico', price: 22.0, unit: 'unidade' },

  // PVC 32 mm
  { id: 'm163', order: 163, name: 'PVC Soldável Tubo 32 mm x 3 m', category: 'hidraulico', price: 22.0, unit: 'unidade' },
  { id: 'm164', order: 164, name: 'PVC Soldável Cap 32 mm', category: 'hidraulico', price: 2.8, unit: 'unidade' },
  { id: 'm165', order: 165, name: 'PVC Soldável Curva 45° 32 mm', category: 'hidraulico', price: 4.2, unit: 'unidade' },
  { id: 'm166', order: 166, name: 'PVC Soldável Curva 90° curta 32 mm', category: 'hidraulico', price: 4.5, unit: 'unidade' },
  { id: 'm167', order: 167, name: 'PVC Soldável Joelho 90° 32 mm', category: 'hidraulico', price: 4.8, unit: 'unidade' },
  { id: 'm168', order: 168, name: 'PVC Soldável Luva 32 mm', category: 'hidraulico', price: 2.4, unit: 'unidade' },
  { id: 'm169', order: 169, name: 'PVC Soldável Tê 90° 32 mm', category: 'hidraulico', price: 4.0, unit: 'unidade' },
  { id: 'm170', order: 170, name: 'PVC Soldável União 32 mm', category: 'hidraulico', price: 5.6, unit: 'unidade' },
  { id: 'm171', order: 171, name: 'PVC Soldável Redução 32x40 mm', category: 'hidraulico', price: 3.5, unit: 'unidade' },
  { id: 'm172', order: 172, name: 'PVC Soldável Adaptador macho rosca 32x1"', category: 'hidraulico', price: 6.5, unit: 'unidade' },
  { id: 'm173', order: 173, name: 'PVC Soldável Adaptador fêmea rosca 32x1"', category: 'hidraulico', price: 6.5, unit: 'unidade' },
  { id: 'm174', order: 174, name: 'PVC Soldável Joelho 90° com bucha latão 32x1"', category: 'hidraulico', price: 15.0, unit: 'unidade' },
  { id: 'm175', order: 175, name: 'PVC Soldável Luva com bucha latão 32x1"', category: 'hidraulico', price: 11.0, unit: 'unidade' },
  { id: 'm176', order: 176, name: 'PVC Soldável Registro esfera 32 mm', category: 'hidraulico', price: 28.0, unit: 'unidade' },

  // PVC 40 mm
  { id: 'm177', order: 177, name: 'PVC Soldável Tubo 40 mm x 3 m', category: 'hidraulico', price: 30.0, unit: 'unidade' },
  { id: 'm178', order: 178, name: 'PVC Soldável Cap 40 mm', category: 'hidraulico', price: 3.5, unit: 'unidade' },
  { id: 'm179', order: 179, name: 'PVC Soldável Curva 45° 40 mm', category: 'hidraulico', price: 5.2, unit: 'unidade' },
  { id: 'm180', order: 180, name: 'PVC Soldável Curva 90° curta 40 mm', category: 'hidraulico', price: 5.8, unit: 'unidade' },
  { id: 'm181', order: 181, name: 'PVC Soldável Joelho 90° 40 mm', category: 'hidraulico', price: 6.0, unit: 'unidade' },
  { id: 'm182', order: 182, name: 'PVC Soldável Luva 40 mm', category: 'hidraulico', price: 3.1, unit: 'unidade' },
  { id: 'm183', order: 183, name: 'PVC Soldável Tê 90° 40 mm', category: 'hidraulico', price: 5.0, unit: 'unidade' },
  { id: 'm184', order: 184, name: 'PVC Soldável União 40 mm', category: 'hidraulico', price: 7.0, unit: 'unidade' },
  { id: 'm185', order: 185, name: 'PVC Soldável Redução 40x50 mm', category: 'hidraulico', price: 4.0, unit: 'unidade' },
  { id: 'm186', order: 186, name: 'PVC Soldável Adaptador macho rosca 40x1.1/4"', category: 'hidraulico', price: 8.0, unit: 'unidade' },
  { id: 'm187', order: 187, name: 'PVC Soldável Joelho 90° com bucha latão 40x1.1/4"', category: 'hidraulico', price: 18.0, unit: 'unidade' },

  // PVC 50 mm
  { id: 'm188', order: 188, name: 'PVC Soldável Tubo 50 mm x 3 m', category: 'hidraulico', price: 42.0, unit: 'unidade' },
  { id: 'm189', order: 189, name: 'PVC Soldável Cap 50 mm', category: 'hidraulico', price: 4.8, unit: 'unidade' },
  { id: 'm190', order: 190, name: 'PVC Soldável Curva 45° 50 mm', category: 'hidraulico', price: 7.0, unit: 'unidade' },
  { id: 'm191', order: 191, name: 'PVC Soldável Curva 90° curta 50 mm', category: 'hidraulico', price: 7.8, unit: 'unidade' },
  { id: 'm192', order: 192, name: 'PVC Soldável Joelho 90° 50 mm', category: 'hidraulico', price: 8.0, unit: 'unidade' },
  { id: 'm193', order: 193, name: 'PVC Soldável Luva 50 mm', category: 'hidraulico', price: 4.2, unit: 'unidade' },
  { id: 'm194', order: 194, name: 'PVC Soldável Tê 90° 50 mm', category: 'hidraulico', price: 6.8, unit: 'unidade' },
  { id: 'm195', order: 195, name: 'PVC Soldável União 50 mm', category: 'hidraulico', price: 9.5, unit: 'unidade' },
  { id: 'm196', order: 196, name: 'PVC Soldável Adaptador macho rosca 50x1.1/2"', category: 'hidraulico', price: 10.0, unit: 'unidade' },
  { id: 'm197', order: 197, name: 'PVC Soldável Joelho 90° com bucha latão 50x1.1/2"', category: 'hidraulico', price: 22.0, unit: 'unidade' },

  // OTHER HYDRAULIC
  { id: 'm198', order: 198, name: 'Registro de Gaveta 3/4"', category: 'hidraulico', price: 45.0, unit: 'unidade' },
  { id: 'm199', order: 199, name: 'Torneira Cozinha Parede', category: 'hidraulico', price: 85.0, unit: 'unidade' },
  { id: 'm200', order: 200, name: 'Sifão Universal Branco', category: 'hidraulico', price: 12.0, unit: 'unidade' },
  { id: 'm201', order: 201, name: 'Fita Veda Rosca 18mm x 10m', category: 'hidraulico', price: 4.5, unit: 'unidade' },
  { id: 'm202', order: 202, name: 'Boia para Caixa d\'Água 3/4"', category: 'hidraulico', price: 35.0, unit: 'unidade' },
  { id: 'm203', order: 203, name: 'Válvula de Descarga', category: 'hidraulico', price: 120.0, unit: 'unidade' },
  { id: 'm204', order: 204, name: 'Ralo Sifonado 100x100x40', category: 'hidraulico', price: 18.0, unit: 'unidade' },
];

export const INITIAL_SERVICES: Service[] = [
  // Electrical
  { id: 's1', name: 'Instalar Tomada', category: 'eletrico', basePrice: 75.0, suggestedMaterials: ['m8', 'm10', 'm2', 'm14'] },
  { id: 's2', name: 'Trocar Tomada', category: 'eletrico', basePrice: 55.0, suggestedMaterials: ['m8'] },
  { id: 's3', name: 'Instalar Interruptor', category: 'eletrico', basePrice: 70.0, suggestedMaterials: ['m9', 'm10', 'm1'] },
  { id: 's4', name: 'Instalar Luminária', category: 'eletrico', basePrice: 120.0, suggestedMaterials: ['m12', 'm14'] },
  { id: 's5', name: 'Instalar Ventilador de Teto', category: 'eletrico', basePrice: 220.0, suggestedMaterials: ['m1', 'm13'] },
  { id: 's6', name: 'Trocar Disjuntor', category: 'eletrico', basePrice: 85.0, suggestedMaterials: ['m5', 'm6'] },
  { id: 's7', name: 'Instalar Quadro de Disjuntores', category: 'eletrico', basePrice: 550.0, suggestedMaterials: ['m7', 'm13'] },
  { id: 's8', name: 'Instalar Chuveiro Elétrico', category: 'eletrico', basePrice: 140.0, suggestedMaterials: ['m14', 'm13'] },
  { id: 's9', name: 'Instalar Aterramento', category: 'eletrico', basePrice: 450.0, suggestedMaterials: ['m3'] },
  { id: 's10', name: 'Instalar Sensor de Presença', category: 'eletrico', basePrice: 110.0, suggestedMaterials: ['m1'] },
  { id: 's11', name: 'Instalar Fita LED', category: 'eletrico', basePrice: 160.0, suggestedMaterials: [] },
  { id: 's12', name: 'Trocar Fiação Elétrica (Ponto)', category: 'eletrico', basePrice: 180.0, suggestedMaterials: ['m2', 'm3', 'm4'] },
  { id: 's13', name: 'Instalar Campainha', category: 'eletrico', basePrice: 95.0, suggestedMaterials: [] },
  { id: 's14', name: 'Instalar Tomada 220v', category: 'eletrico', basePrice: 190.0, suggestedMaterials: ['m4'] },
  { id: 's15', name: 'Instalar Tomada USB', category: 'eletrico', basePrice: 105.0, suggestedMaterials: [] },
  
  // Hydraulic
  { id: 's101', name: 'Instalar Torneira', category: 'hidraulico', basePrice: 90.0, suggestedMaterials: ['m199', 'm201'] },
  { id: 's102', name: 'Trocar Torneira', category: 'hidraulico', basePrice: 80.0, suggestedMaterials: ['m199', 'm201'] },
  { id: 's103', name: 'Instalar Registro', category: 'hidraulico', basePrice: 180.0, suggestedMaterials: ['m198', 'm201'] },
  { id: 's104', name: 'Trocar Registro', category: 'hidraulico', basePrice: 220.0, suggestedMaterials: ['m198', 'm201'] },
  { id: 's105', name: 'Instalar Sifão', category: 'hidraulico', basePrice: 75.0, suggestedMaterials: ['m200'] },
  { id: 's106', name: 'Trocar Sifão', category: 'hidraulico', basePrice: 65.0, suggestedMaterials: ['m200'] },
  { id: 's107', name: 'Instalar Caixa d\'Água', category: 'hidraulico', basePrice: 650.0, suggestedMaterials: [] },
  { id: 's108', name: 'Trocar Boia', category: 'hidraulico', basePrice: 110.0, suggestedMaterials: ['m202', 'm201'] },
  { id: 's109', name: 'Desentupir Pia', category: 'hidraulico', basePrice: 250.0, suggestedMaterials: [] },
  { id: 's110', name: 'Desentupir Vaso', category: 'hidraulico', basePrice: 350.0, suggestedMaterials: [] },
  { id: 's111', name: 'Instalar Chuveiro', category: 'hidraulico', basePrice: 140.0, suggestedMaterials: ['m201'] },
  { id: 's112', name: 'Instalar Ralo', category: 'hidraulico', basePrice: 180.0, suggestedMaterials: ['m204'] },
  { id: 's113', name: 'Trocar Cano PVC', category: 'hidraulico', basePrice: 280.0, suggestedMaterials: ['m148', 'm152', 'm154'] },
  { id: 's114', name: 'Instalar Filtro de Água', category: 'hidraulico', basePrice: 130.0, suggestedMaterials: [] },
];
